// server/src/consumers/persistenceConsumer.js
// ─────────────────────────────────────────────────────────
//  Reads from raw-events topic, writes to Postgres events table.
//
//  Consumer group: persistence-consumer-group
//  Topic:          raw-events
//  Guarantee:      at-least-once delivery (manual offset commit
//                  after successful DB write)
//
//  At-least-once means: if the process crashes after writing to
//  Postgres but before committing the offset, the event will be
//  processed again on restart. The events table uses a UUID
//  primary key generated by the producer — duplicate messages
//  produce duplicate rows. If idempotency matters, add an
//  ON CONFLICT DO NOTHING to the INSERT.
// ─────────────────────────────────────────────────────────

'use strict';

const { createConsumer } = require('../config/kafka');
const { query } = require('../config/database');
const env = require('../config/env');
const logger = require('../utils/logger');

const consumer = createConsumer(env.kafka.groupId.persistence);

/**
 * Parse and validate a raw Kafka message.
 * Returns null if the message is malformed — we log and skip
 * rather than crash the consumer on bad data.
 */
function parseMessage(message) {
  try {
    const value = JSON.parse(message.value.toString());

    // Minimum required fields — anything missing is a producer bug
    if (!value.id || !value.tenantId || !value.eventType) {
      logger.warn({ value }, '[persistenceConsumer] Skipping malformed message — missing required fields');
      return null;
    }

    return value;
  } catch (err) {
    logger.error({ err, raw: message.value?.toString() }, '[persistenceConsumer] Failed to parse message');
    return null;
  }
}

/**
 * Persist a single enriched event to Postgres.
 */
async function persistEvent(event) {
  await query(
    `INSERT INTO events (
      id, created_at, tenant_id, event_type,
      user_id, session_id, properties,
      kafka_topic, kafka_partition, kafka_offset
    ) VALUES (
      $1, $2, $3, $4,
      $5, $6, $7,
      $8, $9, $10
    )
    ON CONFLICT (id, created_at) DO NOTHING`,
    // ON CONFLICT handles at-least-once redelivery — safe to re-insert
    [
      event.id,
      event.timestamp || event.receivedAt,
      event.tenantId,
      event.eventType,
      event.userId       || null,
      event.sessionId    || null,
      JSON.stringify(event.properties || {}),
      event._meta?.topic     || null,
      event._meta?.partition || null,
      event._meta?.offset    || null,
    ]
  );
}

/**
 * Start the persistence consumer.
 * Called once from index.js after infrastructure is connected.
 */
async function start() {
  await consumer.connect();
  logger.info('[persistenceConsumer] Connected');

  await consumer.subscribe({
    topic: env.kafka.topics.rawEvents,
    fromBeginning: false,
    // fromBeginning: false — on first start, begin from the latest
    // offset. This prevents replaying all historical events on
    // every fresh deployment. Set to true only for backfill jobs.
  });

  await consumer.run({
    // autoCommit: false — we commit offsets manually AFTER the DB
    // write succeeds. If the write fails, the offset is not advanced
    // and the message will be redelivered on the next poll.
    autoCommit: false,

    eachMessage: async ({ topic, partition, message }) => {
      const event = parseMessage(message);

      if (!event) {
        // Malformed message — commit offset and move on.
        // Don't let one bad message block the entire partition.
        await consumer.commitOffsets([{
          topic,
          partition,
          offset: (BigInt(message.offset) + 1n).toString(),
        }]);
        return;
      }

      try {
        // Attach Kafka metadata for debugging/replay tracking
        event._meta = {
          ...event._meta,
          topic,
          partition,
          offset: message.offset,
        };

        await persistEvent(event);

        // Commit offset only after successful DB write
        await consumer.commitOffsets([{
          topic,
          partition,
          offset: (BigInt(message.offset) + 1n).toString(),
        }]);

        logger.debug({
          eventId:   event.id,
          eventType: event.eventType,
          tenantId:  event.tenantId,
          partition,
          offset:    message.offset,
        }, '[persistenceConsumer] Event persisted');

      } catch (err) {
        // DB write failed — do NOT commit offset.
        // KafkaJS will redeliver this message on the next poll.
        // Log with full context for alerting/debugging.
        logger.error({
          err,
          eventId:   event.id,
          partition,
          offset:    message.offset,
        }, '[persistenceConsumer] Failed to persist event — offset not committed');

        // Do not rethrow — rethrowing crashes the consumer entirely.
        // The uncommitted offset guarantees redelivery automatically.
      }
    },
  });
}

/**
 * Graceful shutdown — called from index.js SIGTERM handler.
 */
async function stop() {
  await consumer.disconnect();
  logger.info('[persistenceConsumer] Disconnected');
}

module.exports = { start, stop };